version: '3.3'
services:
  db:
    image: mysql:8.1.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  fireapp:
    image: ghcr.io/techlauncherfireapp/backend:latest
    environment:
      username: 'user'
      password: 'password'
      host: 'db'
      port: '3306'
      dbname: 'db'
    ports:
      - '5000:5000'
    depends_on:
      - db
# Names our volume
volumes:
  my-db:
