# This workflow will install Python dependencies and run tests with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Unit and Functional Pytest

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  SQLALCHEMY_DATABASE_URI: "sqlite:///:memory:"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install snapd
      run: |
        sudo apt update
        sudo apt install snapd
    - name: Install MiniZinc
      run: |
        sudo snap install minizinc --classic
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install minizinc
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest
